language: php

php:
 - 5.3
 - 5.5

services:
 - mysql

env:
 - CI_ENV=testing

install:
 - composer install

before_script:
 - chmod +x ./test.sh
 - php vendor-dependencies/kenjis/ci-phpunit-test/install.php

script:
 - ./test.sh